# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cor_meanSd <- function(data, size, replace, n_repetitions, zero_precision = 0.000001) {
    .Call(`_meNet_cor_meanSd`, data, size, replace, n_repetitions, zero_precision)
}

cor_prTest <- function(data, n_repetitions, alternative, zero_precision = 0.000001) {
    .Call(`_meNet_cor_prTest`, data, n_repetitions, alternative, zero_precision)
}

